name: saltstack-repositorio-formula
source: https://github.com/bechtoldt/saltstack-repositorio-formula
summary: SaltStack Formula to set up and configure repositor.io, a tool to create and manage Linux repositories
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - install Rex::Repositorio itself
